---

- name: Create a mongodb-org-4.4.repo file so that you can install MongoDB directly using yum
  copy: src=mongodb-org-4.4.repo dest=/etc/yum.repos.d/mongodb-org-4.4.repo
  become: yes

- name: Install the mongodb package
  yum:
    name:
      - mongodb-org
      - python3
      - pip3
    state: present
  become: yes

- name: Install pymongo
  pip:
    name: pymongo
    executable: pip3

- name: Start service httpd, if not started
  service:
    name: mongod
    state: started
    enabled: yes
  become: yes
