---

- name: Create a mongodb-org-4.4.repo file so that you can install MongoDB directly using yum
  copy: src=mongodb-org-4.4.repo dest=/etc/yum.repos.d/mongodb-org-4.4.repo
  become: yes

- name: Install mongodb-org
  yum:
    name:
      - mongodb-org
    state: present
  become: yes

- name: Install python3
  yum:
    name:
      - python3
    state: present
  become: yes

- name: Install pip3
  yum:
    name:
      - python3-pip
    state: present
  become: yes

#- name: Install pymongo
#  command: python3 -m pip install pymongo
#  become: yes

#- name: Install pymongo
#  pip:
#    name: pymongo
#    state: present
#    executable: pip3
#  become: yes

- name: Start service mongod, if not started
  service:
    name: mongod
    state: started
    enabled: yes
  become: yes
